// automatically generated by the FlatBuffers compiler, do not modify

package LeagueToolkit.IO.ReleaseManifestFile

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
@kotlin.ExperimentalUnsignedTypes
class ReleaseManifestBundleChunk : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ReleaseManifestBundleChunk {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val compressedSize : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val uncompressedSize : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_3_3()
        fun getRootAsReleaseManifestBundleChunk(_bb: ByteBuffer): ReleaseManifestBundleChunk = getRootAsReleaseManifestBundleChunk(_bb, ReleaseManifestBundleChunk())
        fun getRootAsReleaseManifestBundleChunk(_bb: ByteBuffer, obj: ReleaseManifestBundleChunk): ReleaseManifestBundleChunk {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createReleaseManifestBundleChunk(builder: FlatBufferBuilder, id: ULong, compressedSize: UInt, uncompressedSize: UInt) : Int {
            builder.startTable(3)
            addID(builder, id)
            addUncompressedSize(builder, uncompressedSize)
            addCompressedSize(builder, compressedSize)
            return endReleaseManifestBundleChunk(builder)
        }
        fun startReleaseManifestBundleChunk(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addID(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addCompressedSize(builder: FlatBufferBuilder, compressedSize: UInt) = builder.addInt(1, compressedSize.toInt(), 0)
        fun addUncompressedSize(builder: FlatBufferBuilder, uncompressedSize: UInt) = builder.addInt(2, uncompressedSize.toInt(), 0)
        fun endReleaseManifestBundleChunk(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
